#### 2.a

In [2]:
import numpy as np
def design_matrix_simple(temperature: np.ndarray, time: np.ndarray) -> np.ndarray:
    """Returns the design matrix [1, temperature]
    


    Args:
        temperature (np.ndarray): Numpy array of shape [observations]
        time (np.ndarray): Numpy array of shape [observations]

    Returns:
        np.ndarray: Numpy array of shape [observations, 2]
    """

    a = np.ndarray((temperature.shape[0],2))

    for k in range (temperature.shape[0]):
      a[k,0]=temperature[k]
      
      a[k,1]=1


    return(a)

np.testing.assert_allclose(
            design_matrix_simple(
                np.asarray([22, 23, 35], dtype=np.float64),
                np.asarray([0.1, 0.2, 0.3], dtype=np.float64)
            ),
            np.asarray([[22, 1], [23, 1], [35, 1]]))
    Expecting nothing

In [3]:
temp = np.asarray([22, 23, 35], dtype=np.float64)
time = np.asarray([0.1, 0.2, 0.3])

b = design_matrix_simple(temp, time)
print(b)
print(temp.shape)

[[22.  1.]
 [23.  1.]
 [35.  1.]]
(3,)


#### 2.b

In [4]:
def linear_regression_predict(X: np.ndarray, w: np.ndarray) -> np.ndarray:
    """Computes $y = Xw$

    Args:
        X (np.ndarray): Numpy array of shape [observations, features]
        -> observations : le nombre de ligne ! features le nombre de chose qu'on va multiplier 
        w (np.ndarray): Numpy array of shape [features, 1]

    Returns:
        np.ndarray: Numpy array of shape [observations, 1]
    """
    
    y = np.ndarray((X.shape[0],1))

    for k in range(X.shape[0]): # On itère sur le nombre de ligne 
        for l in range (X.shape[1]):
            y[k,0]+= X[k,l]*w[l]


In [5]:
x = np.zeros([10, 2], dtype=np.float64),
w = np.zeros([2, 1], dtype=np.float64)
linear_regression_predict(x,w)

AttributeError: 'tuple' object has no attribute 'shape'

# 2.c

In [6]:
def rmse(y, y_pred):
    return np.sqrt(((y - y_pred) ** 2).mean())

def linear_regression_optimize(y: np.ndarray, X: np.ndarray) -> np.ndarray:
    """Optimizes MSE fit of $y = Xw$

    Args:
        y (np.ndarray): Numpy array of shape [observations, 1]
        X (np.ndarray): Numpy array of shape [observations, features]
        ->on a n lignes pour toutes nos observations et l colonnes pour les features 

    Returns:
        Numpy array of shape [features, 1]

        -> on veut w à partir de x et y 

        tant que MSE baisse on baisse on continue de modifier w 

        comment on modifie w ? chaque features ? comment on le modifie ? 
    """
    X_t = np.transpose(X)
    inter_0= np.dot(X_t,X)
    inv = np.linalg.inv(inter_0)
    inter_1 = np.dot(X_t, y)
    w = np.dot(inv,inter_1)
    return(w)
        





In [7]:
y = np.zeros((15,1))
print(type(y))
y.shape[1]

<class 'numpy.ndarray'>


1

# 3.a

In [8]:
def ridge_regression_optimize(y: np.ndarray, X: np.ndarray, hyperparameter: float) -> np.ndarray:
    X_t = np.transpose(X)
    inter_0= np.dot(X_t,X)

    Id = np.eye(X.shape[1])
    inter_1 = inter_0 + hyperparameter*Id
    inter_2 = np.linalg.inv(inter_1)
    inter_3 = np.dot(X_t,y)
    w = np.dot(inter_2,inter_3)
    return(w)
    """Optimizes MSE fit of $y = Xw$ with L2 regualization

    Args:
        y (np.ndarray): Numpy array of shape [observations, 1]
        X (np.ndarray): Numpy array of shape [observations, features]
        hyperparameter (float): Lambda used in L2 regularization

    Returns:
        Numpy array of shape [features, 1]
    """



    

# 3.b

In [11]:
def cross_validation(y: np.ndarray, X: np.ndarray, splits=3, seed=0):
    """Generates cross validation splits 

    Args:
        y (np.ndarray): Numpy array of shape [observations, 1]
        X (np.ndarray): Numpy array of shape [observations, features]
        splits (int): The number of cross validation splits
        seed (int): The random seed used to shuffle the data.

    Yields:
        Tuple[
            Tuple[np.ndarray, np.ndarray],
            Tuple[np.ndarray, np.ndarray],
        ]: Two (y, X) tuples. First the training split, then the validation split.
    """
    obs = X.shape[0]

    # Because the dataset is not iid. wrt. the index,
    # it is important to shuffle it
    rng = np.random.default_rng(seed)
    perm = rng.permutation(obs)
    y = y[perm, :]
    X = X[perm, :]
    fold_1_valid = (y[0: obs/3,:],X[0: obs/3,:])
    fold_1 = (y[obs/3 : obs ,:],X[obs/3 : obs ,:])
    fold_2_valid = (y[obs/3: 2*obs/3,:],X[obs/3: 2*obs/3,:])

    fold_3_valid = (y[2*obs/3 : obs,:],X[2*obs/3: obs,:])
    fold_1 = np.concatenate(fold_2_valid, fold_3_valid)
    fold_2 = np.concatenate(fold_1_valid, fold_3_valid, fold_3_valid)
    print(fold_2)
    fold_2 = np.concatenate(fold_1_valid, fold_3_valid)
    print(fold_2)
    fold_3= np.concatenate(fold_1_valid, fold_2_valid)
    L_fold= [fold_1, fold_2, fold_3]
    L_valid = [fold_1_valid, fold_2_valid, fold_3_valid]
    for split in range(splits):
        (y_train, X_train), (y_valid, X_valid)= L_fold[split], L_valid[split]
        yield ((y_train, X_train), (y_valid, X_valid))


In [14]:



x = np.arange(9.0)
y = np.arange(9.0)
L_x = np.split(x, 3)

L_y = np.split(y, 3)
#L_x_train= [np.concatenate(L_x[1], L_x[2]), np.concatenate(L_x[0], L_x[2]),np.concatenate(L_x[0], L_x[1])]

print(np.concatenate((L_x[0], L_x[1])))
print(np.concatenate((L_x[0], L_x[1], L_x[0])))
#L_y_train= [np.concatenate(L_y[1], L_y[2]), np.concatenate(L_y[0], L_y[2]),np.concatenate(L_y[0], L_y[1])]

[0. 1. 2. 3. 4. 5.]
[0. 1. 2. 3. 4. 5. 0. 1. 2.]


In [18]:
def cross_validation(y: np.ndarray, X: np.ndarray, splits=3, seed=0):
    """Generates cross validation splits 

    Args:
        y (np.ndarray): Numpy array of shape [observations, 1]
        X (np.ndarray): Numpy array of shape [observations, features]
        splits (int): The number of cross validation splits
        seed (int): The random seed used to shuffle the data.

    Yields:
        Tuple[
            Tuple[np.ndarray, np.ndarray],
            Tuple[np.ndarray, np.ndarray],
        ]: Two (y, X) tuples. First the training split, then the validation split.
    """
    obs = X.shape[0]
    

    # Because the dataset is not iid. wrt. the index,
    # it is important to shuffle it
    rng = np.random.default_rng(seed)
    perm = rng.permutation(obs)
    y = y[perm, :]
    X = X[perm, :]

    # In case 
    L_x = np.split(X, splits)
    L_y = np.split(y, splits)
    L_x_train = L_x
    L_y_train = L_y
    for k in range (splits): 
        liste_index = [i for i in range (splits)]
        liste_index.remove(k)
        inter = L_x [liste_index[0]]
        inter2 = L_y [liste_index[0]]
        for l in range(1, len(liste_index)):
            inter = np.concatenate(inter,L_x[liste_index[l]])
            inter2 = np.concatenate(inter,L_y[liste_index[l]])
        L_x_train[k]= inter
        L_y_train[k]= inter2

    for split in range(splits):

        (y_train, X_train), (y_valid, X_valid)= (L_y_train[split], L_x_train[split]), (L_y[split], L_x[split])
   
        yield ((y_train, X_train), (y_valid, X_valid))

In [37]:
gen = cross_validation(np.asarray([[10], [20], [30]]), np.asarray([[11, 12], [21, 22], [31, 32]]), splits=3, seed=0)

In [40]:
next(gen)

((array([[10, 20, 10, 20, 20]]),
  array([[11, 12, 21, 22, 11, 12, 21, 22, 21, 22]])),
 (array([[10, 20, 10, 20, 20]]),
  array([[11, 12, 21, 22, 11, 12, 21, 22, 21, 22]])))

In [36]:
def cross_validation(y: np.ndarray, X: np.ndarray, splits=3, seed=0):
    """Generates cross validation splits 

    Args:
        y (np.ndarray): Numpy array of shape [observations, 1]
        X (np.ndarray): Numpy array of shape [observations, features]
        splits (int): The number of cross validation splits
        seed (int): The random seed used to shuffle the data.

    Yields:
        Tuple[
            Tuple[np.ndarray, np.ndarray],
            Tuple[np.ndarray, np.ndarray],
        ]: Two (y, X) tuples. First the training split, then the validation split.
    """
    obs = X.shape[0]
    

    # Because the dataset is not iid. wrt. the index,
    # it is important to shuffle it
    rng = np.random.default_rng(seed)
    perm = rng.permutation(obs)
    y = y[perm, :]
    X = X[perm, :]

    # In case 
    L_x = np.split(X, splits)
    L_y = np.split(y, splits)
    L_x_train = L_x
    L_y_train = L_y
    for k in range (splits): 
        liste_index = [i for i in range (splits)]
        liste_index.remove(k)
        inter = L_x [liste_index[0]]
        inter2 = L_y [liste_index[0]]
        for l in range(1, len(liste_index)):
            inter = np.concatenate((inter,L_x[liste_index[l]]), axis=1)
            inter2 = np.concatenate((inter2,L_y[liste_index[l]]), axis = 1)
        L_x_train[k]= inter
        L_y_train[k]= inter2

    for split in range(splits):

        (y_train, X_train), (y_valid, X_valid)= (L_y_train[split], L_x_train[split]), (L_y[split], L_x[split])

        yield ((y_train, X_train), (y_valid, X_valid))


# 3.c

In [ ]:
import pandas as pd
my_list = [[ ' Tom', 'Mark', 'Tony' ],[ ' Tom', 'Mark', 'Tony' ],[ ' Tom', 'Mark', 'Tony' ]]
df = pd.DataFrame(my_list, index = [ 'i.', 'ii.', 'iii.' ],columns = ['Names','Names','Names'])
print(df)

     Names Names Names
i.     Tom  Mark  Tony
ii.    Tom  Mark  Tony
iii.   Tom  Mark  Tony


# 4.a

In [ ]:
from math import sqrt
def ridge_regression_gradient(y: np.ndarray, X: np.ndarray, w: np.ndarray, hyperparameter: float) -> np.ndarray:
    """Compute the gradient of w with respect to the loss
    
    Args:
        y (np.ndarray): Numpy array of shape [observations, 1]
        X (np.ndarray): Numpy array of shape [observations, features]
        w (np.ndarray): Numpy array of shape [features, 1], where the last value is w_0 and all other values represent w_1
        hyperparameter (float): Lambda used in L2 regularizer
        
    Returns:
        np.ndarray: Gradient of w with respect to the loss, as a numpy array of the same shape as w.
    """
    grad = w
    N = X.shape[0]
    y_pred = np.dot(X,w)
    mean_error = 0
    for k in range ( N): 
        mean_error += y_pred[k]-y[k]
    for k in range (w.shape[0]):
        x = sqrt(np.dot(X,np.transpose(X)))
        grad[k]= (1/N)*mean_error*(x**k)
    

In [ ]:
y = np.asarray([[0.5], [-0.5], [1.4]], dtype=np.float64),
X = np.asarray([[-0.3, 0.1], [0.2, 1.1], [-0.45, -0.77]], dtype=np.float64),
w = np.asarray([ [-0.12],[0.8]], dtype=np.float64),
y_pred = np.dot(X,w)
print(y_pred)
norme = (0.12**2+0.8**2)**1/2
#print(X[0])
#print(y_pred)
#print(y_pred[0])
#print(y_pred[0][1][0][0])
print(X[0][0][0])
somme = 0 
y_pred = np.dot(X,w)
for k in range(len(y_pred[0])):
    somme += (y_pred[0][k][0][0] - y[0][k])*X[0][k][0]
print(somme/3 + 0.2*norme)
#print(somme/3)


[[[[ 0.116]]

  [[ 0.856]]

  [[-0.562]]]]
-0.3
[0.48854]


In [ ]:
X = [[-0.3, 0.1], [0.2, 1.1], [-0.45, -0.77]]
w = [-0.12, 0.8 ]
somme = 0 
for k in range (3): 

    for i in range(2):
        somme += (w[i] * X[k][i])**2
print(somme - 1.4)


-0.2349559999999995


In [ ]:
2*0.12*0.1

0.024

In [ ]:
3*1.92

5.76

In [ ]:
somme = -0.12*3 - 0.024
X = [0.1, 1.25, 0.7954]
X1 = [0.316, 1.11, -0.89]
X2 = [-0.3, 0.2, -0.45]
for k in range (3): 
    somme += 0.8 * X1[k]
print(somme - 1.4)

-1.3552


In [ ]:
X = [[-0.3, 0.1], [0.2, 1.1], [-0.45, -0.77]]
w = [ -0.12,0.8 ]
y = [[0.5], [-0.5], [1.4]]
    ## on constitue les prédictions 
y_pred = np.dot(X,w)
norme = 0 
for k in range(len(w)): 
      norme+= w[k]**2
norme = sqrt(norme)
Liste = [0 for k in range (len(w))]
print(Liste)
grad = w 
for k in range(len(y_pred)):
      for i in range(len(Liste)):

            Liste[i] += (y_pred[k] - y[k])*X[k][i]
            print('la diff', y_pred[k] - y[k], 'multiplié',(y_pred[k] - y[k])*X[k][i])

print(Liste)
for l in range(len(Liste)): 

      grad[l]=Liste[l]/3 + 0.2*norme

print(grad)

[0, 0]
la diff [-0.384] multiplié [0.1152]
la diff [-0.384] multiplié [-0.0384]
la diff [1.356] multiplié [0.2712]
la diff [1.356] multiplié [1.4916]
la diff [-1.962] multiplié [0.8829]
la diff [-1.962] multiplié [1.51074]
[array([1.2693]), array([2.96394])]
[array([0.58488999]), array([1.14976999])]


In [69]:
from math import sqrt

def ridge_regression_gradient(y: np.ndarray, X: np.ndarray, w: np.ndarray, hyperparameter: float) -> np.ndarray:
    """Compute the gradient of w with respect to the loss
    
    Args:
        y (np.ndarray): Numpy array of shape [observations, 1]
        X (np.ndarray): Numpy array of shape [observations, features]
        w (np.ndarray): Numpy array of shape [features, 1], where the last value is w_0 and all other values represent w_1
        hyperparameter (float): Lambda used in L2 regularizer
        
    Returns:
        np.ndarray: Gradient of w with respect to the loss, as a numpy array of the same shape as w.
        """

    ## on constitue les prédictions 
    y_pred = np.dot(X,w)
    norme = 0 
    for k in range(len(w)): 
          norme+= w[k]**2
    norme = sqrt(norme)
    Liste = [0 for k in range (len(w))]

    grad = w 
    for k in range(len(y_pred)):
          for i in range(len(Liste)):

                Liste[i] += (y_pred[k] - y[k])*X[k][i]


    for l in range(len(Liste)): 

          grad[l]=Liste[l]/3 + 2*hyperparameter*w[l]


    return(grad)

def ridge_regression_gradient_descent(y_train: np.ndarray, X_train: np.ndarray,
                                      y_val: np.ndarray, X_val: np.ndarray,
                                      w_init: np.ndarray, hyperparameter: float,
                                      learning_rate: float, num_steps: int) -> np.ndarray:
    """ Runs gradient descent to optimize the parameters w.
    
    Args:
        y_train (np.ndarray): Numpy array of shape [observations, 1]
        X_train (np.ndarray): Numpy array of shape [observations, features]
        y_val (np.ndarray): Numpy array of shape [observations, 1]
        X_val (np.ndarray): Numpy array of shape [observations, features]
        w_init (np.ndarray): Numpy array of shape [features, 1]
        hyperparameter (float): Lambda used in L2 regularizer
        learning_rate (float): Value to multiply our gradient with before updating our parameters.
        num_steps (int): Number of gradient descent steps to perform.
    
    Returns:
        train_loss (np.ndarray): The train RMSE loss without L2 regularizer, for each step.
        val_loss (np.ndarray): The validation RMSE loss without L2 regularizer, for each step.
        optimized_w (np.ndarray): The optimized w parameters.
    """
    train_losses = np.zeros((num_steps,), dtype=np.float32)  # You will need to update this
    val_losses = np.zeros((num_steps,), dtype=np.float32)  # You will need to update this
    w_sol = np.copy(w_init)  # You will need to update this
    print(w_init)
    w = w_init
    X = np.concatenate((X_train, X_val))
    y = np.concatenate((y_train, y_val))

    if num_steps > 1 : 
        for k in range (num_steps):
            #train_losses[k] = rmse (linear_regression_predict(X_train,w_sol), y_train)
            #val_losses[k] = rmse (linear_regression_predict(X_val,w_sol), y_val)
            grad = ridge_regression_gradient(y_train,X_train,w_sol,hyperparameter)
            w = w - grad*learning_rate
    
    else : 
            #train_losses[k] = rmse (linear_regression_predict(X_train,w_sol), y_train)
            #val_losses[k] = rmse (linear_regression_predict(X_val,w_sol), y_val)
            grad = ridge_regression_gradient(y_train,X_train,w_sol,hyperparameter)
            w = w_init - grad*learning_rate
    ...

    return (train_losses, val_losses, w_init - grad*learning_rate)


In [58]:
grad = [1.80054, 0.380551]

In [72]:
ridge_regression_gradient_descent(np.array(([[0.5], [-0.5], [1.4]])) ,np.array(([[-0.3, 0.1], [0.2, 1.1], [-0.45, -0.77]])) ,np.array(([[0.76], [0.13], [-0.82]])) ,np.array(([[1.04, -0.4], [0.9, 0.1], [-0.5, 0.47]])) ,np.asarray(([[0.8], [-0.12]])) ,0.90,1e-3,1)

[[ 0.8 ]
 [-0.12]]


(array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([[ 0.79819946],
        [-0.12038055]]))

 array([[ 0.79619808],
        [-0.12176295]]))