In [23]:
import numpy as np
import random

question 1.3 

In [33]:
a = 12
b = 4

In [25]:
time = np.ndarray((a,b))
time.shape

(3, 4)

In [28]:
time = 0
time

0

In [31]:
time = np.ndarray((1,b))

In [32]:
time

array([[1.22368384e-311, 4.67296746e-307, 1.69121096e-306,
        0.00000000e+000]])

In [48]:
L = []
for k in range (a): 

        L.append(random.randrange(200))
print(L)

[190, 3, 145, 76, 18, 112, 91, 53, 194, 193, 68, 30]


In [51]:
L.sort()
print(L)

[3, 18, 30, 53, 68, 76, 91, 112, 145, 190, 193, 194]


In [20]:
print(time)
print(time.sort(axis=0))

[[123.  64.  21.  83.]
 [177. 120. 102. 154.]
 [ 57. 180. 116. 194.]]
None


In [21]:
time

array([[ 57.,  64.,  21.,  83.],
       [123., 120., 102., 154.],
       [177., 180., 116., 194.]])

In [52]:
a = np.ones([9, 5, 7, 4])
c = np.ones([9, 5, 4, 3])


In [54]:
a

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         ...,
         [1.,

In [53]:
np.dot(a,c)

array([[[[[[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]],

          [[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]],

          [[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]],

          ...,

          [[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]],

          [[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]],

          [[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]]],


         [[[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.]],

          [[4., 4., 4.],
           [4., 4., 4.],
           [4., 4., 4.],
           [4., 4.

In [57]:
loss = 0
loss += np.log(np.exp(0.9)/(np.exp(0.1)+np.exp(0.9)+np.exp(0.4)+np.exp(0.6)))
loss += np.log(np.exp(0.4)/(np.exp(0.1)+np.exp(0.9)+np.exp(0.4)+np.exp(0.6)))
loss/5

-0.5113728914594535

In [64]:
np.log(np.exp(0.4))-np.log((np.exp(0.4)+np.exp(0.1)))

-0.5543552444685271

In [84]:
X = np.array([[1, 2],[1, 1],[1,1]]) 
W = np.array([[1.0, 1.0], [2.0, 2.0], [3.0, 3.0]])

print(np.matmul(X,np.transpose(W)))

[[3. 6. 9.]
 [2. 4. 6.]
 [2. 4. 6.]]


In [82]:
pred = np.array([[1.0, 1.0], [2.0, 2.0], [3.0, 3.0],[1,1]])
X = np.array([[1, 1,2],[1,1, 1],[1,1,1],[1,1,1]]) 
print(pred.shape)
print(X.shape)
np.matmul(np.transpose(pred),X) 

(4, 2)
(4, 3)


array([[7., 7., 8.],
       [7., 7., 8.]])

In [91]:
matrix_a = np.array([[1,1,1],[1,1,1],[1,1,1]])
matrix_b= np.array([[1,1,1],[1,1,1],[1,1,1]])
B = np.broadcast_to(b, W.shape)
B

array([[1, 1],
       [1, 1],
       [1, 1]])

In [92]:
sqrA = np.broadcast_to(np.power(matrix_a, 2), 1).reshape(matrix_a.shape[0], 1)+ (matrix_a.shape[0], matrix_b.shape[0])
sqrB = np.broadcast_to(np.sum(np.power(matrix_b, 2), 1).reshape(matrix_b.shape[0], 1), (matrix_b.shape[0], matrix_a.shape[0])).transpose()

res = np.sqrt(sqrA - 2*np.matmul(matrix_a, matrix_b.transpose()) + sqrB)


ValueError: input operand has more dimensions than allowed by the axis remapping