# Questions 

# Réponses

#### 1.a

In [22]:
import pandas as pd
import string

In [23]:
d = {'col1': ['Great game!', 'It is okay.']}
data = pd.DataFrame(data=d)

In [11]:
df

col1            col2
0  Great game!      Good game.
1  It is okay.  It is alright.

In [12]:
for k in range (len(df)):
    for j in range (len(df.iloc[k,:])): 
        df.iloc[k,j]= df.iloc[k,j].lower()

In [13]:
df

col1            col2
0  great game!      good game.
1  it is okay.  it is alright.

In [16]:
for k in range (len(df)):
    for j in range (len(df.iloc[k,:])): 


        df.iloc[k,j] = df.iloc[k,j].translate(str.maketrans('', '', string.punctuation))

In [17]:
df

col1           col2
0  great game      good game
1  it is okay  it is alright

In [24]:
def remove_punctuation(data) :
    """ Removes punctation marks from data.

    Args:
        data (pandas.Series): a Pandas Series containing the original data

    Returns:
        data_punctuation_free (pandas.Series):a Pandas Series containing the original data withuout punctuation marks
    """
    for k in range (len(data)):
        data.iloc[k] =data.iloc[k].translate(str.maketrans('', '', string.punctuation))
    return data

def set_to_lower_case(data):
    """ Sets all characters in data to lower-case.

    Args:
        data (pandas.Series): a Pandas Series containing the original data

    Returns:
        data_lower_cased (pandas.Series): a Pandas Series containing the original data lower-cased
    """
    for k in range (len(data)):
          data.iloc[k]= data.iloc[k].lower()
    return data

In [25]:
print(remove_punctuation(data))

AttributeError: 'Series' object has no attribute 'translate'

#### 1.b

In [86]:
d = {'col1': ['Great great great game!', 'It okay.','sooo bad', 'It is okay.','Great game!', 'It is okay.','good game', 'bad','Great great great game!', 'It okay.','sooo bad', 'It is okay.','Great game!', 'It is okay.','good game', 'bad','Great great great game!', 'It okay.','sooo bad', 'It is okay.','Great game!', 'It is okay.','good game', 'bad','Great great great game!', 'It okay.','sooo bad', 'It is okay.','Great game!', 'It is okay.','good game', 'bad'],'col2': ['Great great great game!', 'It okay.','sooo bad', 'It is okay.','Great game!', 'It is okay.','good game', 'bad','Great great great game!', 'It okay.','sooo bad', 'It is okay.','Great game!', 'It is okay.','good game', 'bad','Great great great game!', 'It okay.','sooo bad', 'It is okay.','Great game!', 'It is okay.','good game', 'bad','Great great great game!', 'It okay.','sooo bad', 'It is okay.','Great game!', 'It is okay.','good game', 'bad']}
data = pd.DataFrame(data=d)

In [87]:
data.col1 =remove_punctuation(data.col1)
data.col1 =set_to_lower_case(data.col1)

In [88]:
data.col1

0     great great great game
1                    it okay
2                   sooo bad
3                 it is okay
4                 great game
5                 it is okay
6                  good game
7                        bad
8     great great great game
9                    it okay
10                  sooo bad
11                it is okay
12                great game
13                it is okay
14                 good game
15                       bad
16    great great great game
17                   it okay
18                  sooo bad
19                it is okay
20                great game
21                it is okay
22                 good game
23                       bad
24    great great great game
25                   it okay
26                  sooo bad
27                it is okay
28                great game
29                it is okay
30                 good game
31                       bad
Name: col1, dtype: object

#### 1.b

In [140]:
def pick_most_frequent_words(data, vocab_size: int):
    """ Sorts the words in data by frequency in descending order and picks the top vocab_size most frequent words

    Args:
        data (pandas.Series): a Pandas Series containing the original data
        vocab_size (int): the number of top words to pick

    Returns:
        most_frequent_words (list): a list with the top vocab_size most frequent words (in descending order of frequency)
    """
    tous_les_avis=[]
    for k in range (len(data)): 
      tous_les_avis+=data.iloc[k].split()

    unique_words = list(set(tous_les_avis))

    frequency = []
    for words in unique_words :
        frequency.append(tous_les_avis.count(words))
    print(frequency)
    print(unique_words)
    most_frequent_words =[]

    for l in range (vocab_size): 
        most_frequent_words.append(unique_words[frequency.index(max(frequency))])
        frequency[frequency.index(max(frequency))] = 0
    return most_frequent_words



In [178]:
import pandas 
import numpy
def pick_most_frequent_words(data: pandas.Series, vocab_size: int) -> list:
    """ Sorts the words in data by frequency in descending order and picks the top vocab_size most frequent words

    Args:
        data (pandas.Series): a Pandas Series containing the original data
        vocab_size (int): the number of top words to pick

    Returns:
        most_frequent_words (list): a list with the top vocab_size most frequent words (in descending order of frequency)
    """
#version 3
    #we create a list of all the worlds
    tous_les_avis=[]
    for k in range (len(data)): 
      tous_les_avis+=data.iloc[k].split()

    #We create a dictionnary using the unique words 


    unique_words = list(set(tous_les_avis))
    b = len(unique_words)
    indices = [k for k in range(b)]
    dict_mots = dict(zip(unique_words, indices))

    compteur = numpy.zeros((b))

    #We update the value in the dict 
    for k in range(len(tous_les_avis)): 
      a = dict_mots[tous_les_avis[k]]
      print(tous_les_avis[k])
      print(a)
      compteur[a] +=1
    print(compteur)
    print(dict_mots)
    val = numpy.quantile(compteur,(b-vocab_size)/b)
    most_frequent_words=[]
    for k in range (b): 
      if compteur[k]>val: 
        most_frequent_words.append(unique_words[k])

    print('ici')

    return most_frequent_words

In [179]:
vocab = pick_most_frequent_words(data.col1,6)

great
5
great
5
great
5
game
7
it
0
okay
3
sooo
4
bad
6
it
0
is
1
okay
3
great
5
game
7
it
0
is
1
okay
3
good
2
game
7
bad
6
great
5
great
5
great
5
game
7
it
0
okay
3
sooo
4
bad
6
it
0
is
1
okay
3
great
5
game
7
it
0
is
1
okay
3
good
2
game
7
bad
6
great
5
great
5
great
5
game
7
it
0
okay
3
sooo
4
bad
6
it
0
is
1
okay
3
great
5
game
7
it
0
is
1
okay
3
good
2
game
7
bad
6
great
5
great
5
great
5
game
7
it
0
okay
3
sooo
4
bad
6
it
0
is
1
okay
3
great
5
game
7
it
0
is
1
okay
3
good
2
game
7
bad
6
[12.  8.  4. 12.  4. 16.  8. 12.]
{'it': 0, 'is': 1, 'good': 2, 'okay': 3, 'sooo': 4, 'great': 5, 'bad': 6, 'game': 7}
ici


In [180]:
vocab

['it', 'is', 'okay', 'great', 'bad', 'game']

In [92]:
for k in range (len(data)): 
    print(data.col1.iloc[0].split())

['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 'game']
['great', 'great', 'great', 

In [80]:
data.col1

0    Great great great game!
1                   It okay.
2                   sooo bad
3                It is okay.
4                Great game!
5                It is okay.
6                  good game
7                        bad
Name: col1, dtype: object

#### 1.c

In [142]:
data.col1

0     great great great game
1                    it okay
2                   sooo bad
3                 it is okay
4                 great game
5                 it is okay
6                  good game
7                        bad
8     great great great game
9                    it okay
10                  sooo bad
11                it is okay
12                great game
13                it is okay
14                 good game
15                       bad
16    great great great game
17                   it okay
18                  sooo bad
19                it is okay
20                great game
21                it is okay
22                 good game
23                       bad
24    great great great game
25                   it okay
26                  sooo bad
27                it is okay
28                great game
29                it is okay
30                 good game
31                       bad
Name: col1, dtype: object

In [143]:
import numpy
def binary_bow(data, vocab):

    """ Generates a binary vector for each example in data of the size of your vocabulary. Each vector represents which words in the vocabulary are present in each example.

    Args:
        data (numpy.ndarray): the samples to vectorize
        vocab (list): the vocabulary of words

    Returns:
        binary bag-of-words representations (numpy.ndarray): the vectorized samples
    """
    ...
    shape_output= (len(data), len(vocab))
    bag_of_words=numpy.ndarray(shape_output)

    for k in range (len(data)):

        for l in range (len(vocab)):

            if vocab[l] in data.iloc[k]:

                
                bag_of_words[k, l]=1
    return bag_of_words

In [144]:
binary_bow(data.col1, vocab)

array([[1.00000000e+000, 6.95205063e-310, 7.11454530e-321,
        1.00000000e+000, 1.26249627e-311, 0.00000000e+000],
       [8.94213159e+130, 1.00000000e+000, 1.00000000e+000,
        1.39804329e-076, 1.39803697e-076, 8.61260270e-067],
       [7.11326544e-067, 6.01346953e-154, 1.31238422e-047,
        5.20364288e-090, 1.30354289e-076, 1.00000000e+000],
       [5.05218184e-086, 1.00000000e+000, 1.00000000e+000,
        8.94213159e+130, 1.00000000e+000, 9.45332851e-096],
       [1.00000000e+000, 1.39803697e-076, 4.18585465e-062,
        1.00000000e+000, 6.01346953e-154, 6.37258526e-067],
       [5.20653425e-090, 1.00000000e+000, 1.00000000e+000,
        5.05218184e-086, 1.00000000e+000, 1.15298109e-259],
       [8.94213159e+130, 1.45136156e-047, 9.45515729e-096,
        1.00000000e+000, 1.39803697e-076, 4.18585465e-062],
       [7.11326533e-067, 6.01346953e-154, 1.31238422e-047,
        5.20364288e-090, 1.30354289e-076, 1.00000000e+000],
       [1.00000000e+000, 1.65690031e-047, 1.1529

### 2.1

**Question 2.1 (3 points):** Construct the frequency bag-of-words representations for each example in your dataset. To achieve this, start by summing the occurrences of words in a review into a histogram. Then, divide by the sum of occurrences of all 1,000 words so that the vector for each example sums to 1.

In [234]:

def frequency_bow(data: numpy.ndarray, vocab: list) -> numpy.ndarray:
    shape_output= (len(data), len(vocab))
    f_bag_of_words=numpy.zeros(shape_output, dtype = int)
    new_array=numpy.array(shape_output, dtype = int)
    Liste_de_ta_mere =[]
    for k in range (len(data)):
        a = data[k]

        a = str(a)
        for l in range (len(vocab)):
          if vocab[l] in a.split():  

                #print(a.split().count(vocab[l]))
                f_bag_of_words[k, l]=a.split().count(vocab[l])
                #print(f_bag_of_words[k, l])
                #print(f_bag_of_words)
        nbr_occurences = numpy.sum(f_bag_of_words[k,:])
        print(nbr_occurences)
        if nbr_occurences != 0 : 
            Liste_de_ta_mere.append(list(f_bag_of_words[k] / nbr_occurences))
            print(Liste_de_ta_mere)
            #f_bag_of_words = new_array
            print(f_bag_of_words[k])
        if nbr_occurences ==0 : 
            Liste_de_ta_mere.append(list(f_bag_of_words[k]))

    new_array=numpy.array(Liste_de_ta_mere)
    return new_array      
                



In [187]:
d = {'col1': ['Great great great game!', 'It okay.','sooo bad', 'It is okay.','Great game!', 'It is okay.','good game', 'bad','Great great great game!', 
'It okay.','sooo bad', 'It is okay.','Great game!', 'It is okay.','good game', 'bad','Great great great game!', 'It okay.'],
'col2': ['Great great great game!', 'It okay.','sooo bad', 'It is okay.','Great game!', 'It is okay.','good game', 'bad','Great great great game!', 'It okay.',
'sooo bad', 'It is okay.','Great game!', 'It is okay.','good game', 'bad','Great great great game!', 'It okay.']}
data = pd.DataFrame(data=d)

In [190]:
data.col1 = remove_punctuation(data.col1)
data.col1 = set_to_lower_case(data.col1)

In [191]:
data.col1

0     great great great game
1                    it okay
2                   sooo bad
3                 it is okay
4                 great game
5                 it is okay
6                  good game
7                        bad
8     great great great game
9                    it okay
10                  sooo bad
11                it is okay
12                great game
13                it is okay
14                 good game
15                       bad
16    great great great game
17                   it okay
Name: col1, dtype: object

In [235]:
frequency_bow(data.col1, vocab)

4
[[0.0, 0.0, 0.0, 0.75, 0.0, 0.25]]
[0 0 0 3 0 1]
2
[[0.0, 0.0, 0.0, 0.75, 0.0, 0.25], [0.5, 0.0, 0.5, 0.0, 0.0, 0.0]]
[1 0 1 0 0 0]
1
[[0.0, 0.0, 0.0, 0.75, 0.0, 0.25], [0.5, 0.0, 0.5, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 1.0, 0.0]]
[0 0 0 0 1 0]
3
[[0.0, 0.0, 0.0, 0.75, 0.0, 0.25], [0.5, 0.0, 0.5, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [0.3333333333333333, 0.3333333333333333, 0.3333333333333333, 0.0, 0.0, 0.0]]
[1 1 1 0 0 0]
2
[[0.0, 0.0, 0.0, 0.75, 0.0, 0.25], [0.5, 0.0, 0.5, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [0.3333333333333333, 0.3333333333333333, 0.3333333333333333, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.5, 0.0, 0.5]]
[0 0 0 1 0 1]
3
[[0.0, 0.0, 0.0, 0.75, 0.0, 0.25], [0.5, 0.0, 0.5, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [0.3333333333333333, 0.3333333333333333, 0.3333333333333333, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.5, 0.0, 0.5], [0.3333333333333333, 0.3333333333333333, 0.3333333333333333, 0.0, 0.0, 0.0]]
[1 1 1 0 0 0]
1
[[0.0, 0.0, 0.0, 0.75, 0.0, 0.25

array([[0.        , 0.        , 0.        , 0.75      , 0.        ,
        0.25      ],
       [0.5       , 0.        , 0.5       , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.5       , 0.        ,
        0.5       ],
       [0.33333333, 0.33333333, 0.33333333, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.75      , 0.        ,
        0.25      ],
       [0.5       , 0.        , 0.5       , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        ],
       [0.33333333, 0

In [197]:
vocab

['it', 'is', 'okay', 'great', 'bad', 'game']